// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Options.proto</summary>
public static partial class OptionsReflection {

  #region Descriptor
  /// <summary>File descriptor for Options.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static OptionsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1PcHRpb25zLnByb3RvGhBkZXNjcmlwdG9yLnByb3RvOjIKBW1zZ2lkEh8u",
          "Z29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGJFOIAEoBYgBAWIGcHJv",
          "dG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { OptionsExtensions.Msgid }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of Options.proto</summary>
public static partial class OptionsExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int> Msgid =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int>(10001, pb::FieldCodec.ForInt32(80008, 0));
}


#endregion Designer generated code
